terraform-validate:
    runs-on: ubuntu-latest
    name: Terraform Validate
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Configure Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.4
      - name: Terraform Init
        run: terraform init
      - name: Terraform Validate
        run: terraform validate